//! §7.5 generic REST error body and HTTP mapping helpers.

use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde::Serialize;

/// Closed §7.5 error body: `{ "error": "<machine_code>", "message": "<human>" }`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ErrorBody {
    pub error: String,
    pub message: String,
}

/// Public wire text for every `500 internal_error`. Internal diagnostics stay
/// off the wire (absolute paths, OS errors, kernel contract detail) and are
/// carried only in [`ApiError::cause`] / structured logs.
pub const PUBLIC_INTERNAL_MESSAGE: &str = "an internal error occurred";

/// An HTTP error ready to return from a handler.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApiError {
    pub status: StatusCode,
    pub body: ErrorBody,
    /// Operator-facing cause for logs / startup diagnostics. **Never** copied
    /// into the HTTP body by [`IntoResponse`].
    pub(crate) cause: Option<String>,
}

impl ApiError {
    pub fn new(status: StatusCode, error: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            status,
            body: ErrorBody {
                error: error.into(),
                message: message.into(),
            },
            cause: None,
        }
    }

    /// §7.5 `malformed_request` / 400.
    pub fn malformed(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, "malformed_request", message)
    }

    /// §7.5 `bounds_exceeded` / 400 — numeric but outside the closed range
    /// (e.g. `limit` ∉ `1..=1000`). Distinct from `malformed_request`, which
    /// covers non-numeric / overflowing query values.
    pub fn bounds_exceeded(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, "bounds_exceeded", message)
    }

    /// §7.5 `unauthorized` / 401 — API-edge OwnershipProof / capability failures
    /// (wrong domain, bad signature, GrantProof, address mismatch, chan_bind).
    ///
    /// Spec §7.5 L2894 / L2896: missing/invalid/wrong-domain OwnershipProof or
    /// GrantProof → `401 unauthorized`. Generated by the API itself; not from
    /// kernel `ErrorInfo.metadata["http_status"]`. Also Blossom kind-24242
    /// auth-event rejection (§7.4).
    pub fn unauthorized(message: impl Into<String>) -> Self {
        Self::new(StatusCode::UNAUTHORIZED, "unauthorized", message)
    }

    /// §7.5 `scope_exceeded` / 403 — foreign-uploader DELETE, non-peer
    /// replication PUT, resolved-scope violation.
    pub fn scope_exceeded(message: impl Into<String>) -> Self {
        Self::new(StatusCode::FORBIDDEN, "scope_exceeded", message)
    }

    /// §7.5 `not_found` / 404 — unknown `blob_id` (and similar).
    pub fn not_found(message: impl Into<String>) -> Self {
        Self::new(StatusCode::NOT_FOUND, "not_found", message)
    }

    /// §7.5 intro / §6.1: known route whose role feature is off for this
    /// deployment → `404 feature_disabled`. Distinct from a bare axum 404 for
    /// a path that was never registered (including unconfigured Blossom).
    pub fn feature_disabled(message: impl Into<String>) -> Self {
        Self::new(StatusCode::NOT_FOUND, "feature_disabled", message)
    }

    /// §7.5 `payload_too_large` / 413 — Blossom body over the advertised limit.
    pub fn payload_too_large(message: impl Into<String>) -> Self {
        Self::new(StatusCode::PAYLOAD_TOO_LARGE, "payload_too_large", message)
    }

    /// Unsupported request media type / 415 — non-raw Blossom upload body
    /// (multipart or JSON is not a conforming v1 form, §7.4).
    pub fn unsupported_media_type(message: impl Into<String>) -> Self {
        Self::new(
            StatusCode::UNSUPPORTED_MEDIA_TYPE,
            "unsupported_media_type",
            message,
        )
    }

    /// Fail-closed stand-in when the kernel transport breaks or the kernel
    /// violates the ErrorInfo contract. Spec §7.5 closes the enumeration with
    /// `internal_error` / 500 for any condition not listed.
    ///
    /// The public `message` is always [`PUBLIC_INTERNAL_MESSAGE`]. The
    /// diagnostic string is stored in [`Self::cause`] and emitted via
    /// `tracing` only — never forwarded onto the wire.
    pub fn internal(cause: impl Into<String>) -> Self {
        let cause = cause.into();
        tracing::error!(cause = %cause, "internal_error");
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            body: ErrorBody {
                error: "internal_error".to_string(),
                message: PUBLIC_INTERNAL_MESSAGE.to_string(),
            },
            cause: Some(cause),
        }
    }

    /// Operator-facing cause when present (startup / tests). Not the wire body.
    pub fn cause(&self) -> Option<&str> {
        self.cause.as_deref()
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        // Always a §7.5 JSON body — never a bare status with an empty body.
        // (Axum's default 404 fallback is status-only; handlers must not
        // look like that when they intentionally return an ApiError.)
        // `cause` is intentionally dropped here.
        (self.status, Json(self.body)).into_response()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use http_body_util::BodyExt;

    #[tokio::test]
    async fn internal_public_body_is_neutral_cause_stays_off_wire() {
        let err = ApiError::internal(
            "blossom store: cannot create root /var/lib/secret-path: permission denied",
        );
        assert_eq!(err.status, StatusCode::INTERNAL_SERVER_ERROR);
        assert_eq!(err.body.error, "internal_error");
        assert_eq!(err.body.message, PUBLIC_INTERNAL_MESSAGE);
        assert!(
            err.cause().expect("cause retained").contains("secret-path"),
            "operator cause must retain the diagnostic"
        );
        let res = err.clone().into_response();
        let bytes = res.into_body().collect().await.unwrap().to_bytes();
        let text = String::from_utf8(bytes.to_vec()).unwrap();
        assert!(
            !text.contains("secret-path"),
            "public body must not leak the path: {text}"
        );
        assert!(
            !text.contains("permission denied"),
            "public body must not leak the OS error: {text}"
        );
        assert!(text.contains(PUBLIC_INTERNAL_MESSAGE));
    }
}
